// <auto-generated />
using System;
using AcademicClaimsPrototype.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicClaimsPrototype.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251114004438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicClaimsPrototype.Models.Claim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<string>("LecturerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Date = new DateTime(2025, 11, 9, 2, 44, 37, 260, DateTimeKind.Local).AddTicks(9440),
                            Description = "Marking scripts - March 2025",
                            DocumentPath = "/uploads/marking-scripts.pdf",
                            Hours = 10.0,
                            LecturerEmail = "lecturer1@uni.ac.za",
                            Rate = 150.0,
                            Status = 0,
                            SubmittedAt = new DateTime(2025, 11, 9, 0, 44, 37, 260, DateTimeKind.Utc).AddTicks(9452)
                        },
                        new
                        {
                            Id = "2",
                            Date = new DateTime(2025, 11, 12, 2, 44, 37, 260, DateTimeKind.Local).AddTicks(9474),
                            Description = "Invigilating exams - April 2025",
                            DocumentPath = "/uploads/invigilation.pdf",
                            Hours = 8.0,
                            LecturerEmail = "lecturer1@uni.ac.za",
                            ProcessedAt = new DateTime(2025, 11, 13, 2, 44, 37, 260, DateTimeKind.Local).AddTicks(9478),
                            ProcessedBy = "manager@uni.ac.za",
                            Rate = 200.0,
                            Status = 1,
                            SubmittedAt = new DateTime(2025, 11, 12, 0, 44, 37, 260, DateTimeKind.Utc).AddTicks(9487)
                        },
                        new
                        {
                            Id = "3",
                            Date = new DateTime(2025, 11, 13, 2, 44, 37, 260, DateTimeKind.Local).AddTicks(9496),
                            Description = "Setting test papers",
                            DocumentPath = "/uploads/test-paper.pdf",
                            Hours = 5.0,
                            LecturerEmail = "lecturer2@uni.ac.za",
                            ProcessedAt = new DateTime(2025, 11, 14, 2, 44, 37, 260, DateTimeKind.Local).AddTicks(9503),
                            ProcessedBy = "coordinator@uni.ac.za",
                            Rate = 180.0,
                            RejectionReason = "Duplicate task submission",
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 11, 13, 0, 44, 37, 260, DateTimeKind.Utc).AddTicks(9504)
                        });
                });

            modelBuilder.Entity("AcademicClaimsPrototype.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Email = "lecturer1@uni.ac.za",
                            Department = "CS",
                            FullName = "Lecturer One",
                            Password = "123",
                            PhoneNumber = "0810000001",
                            Role = "Lecturer"
                        },
                        new
                        {
                            Email = "lecturer2@uni.ac.za",
                            Department = "IT",
                            FullName = "Lecturer Two",
                            Password = "123",
                            PhoneNumber = "0810000002",
                            Role = "Lecturer"
                        },
                        new
                        {
                            Email = "manager@uni.ac.za",
                            Password = "123",
                            Role = "AcademicManager"
                        },
                        new
                        {
                            Email = "coordinator@uni.ac.za",
                            Password = "123",
                            Role = "ProgrammeCoordinator"
                        },
                        new
                        {
                            Email = "hr@uni.ac.za",
                            Password = "123",
                            Role = "HR"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
